CHUNK_SIZE = 1024
BUFFER_SIZE = 1024
TIMEOUT_DOWNLOAD = 15
TIMEOUT_UPLOAD   = 15

TIMEOUT_TIMER = 15
WINDOW_SIZE   = 5

ENCODING = 'utf-8'
PADDING = '0'
SEQ_LEN = 8

MSG_INTENTION_UPLOAD = 'upload'
MSG_INTENTION_DOWNLOAD = 'download'
MSG_CONNECTION_ACK = 'connection_ack'
MSG_FILE_SIZE = 'file_size'
MSG_FILE_SIZE_ACK = 'file_size_ack'

ERROR_INVALID_PARAMETERS = 'invalid_parameters'
ERROR_INVALID_INTENTION = 'invalid_intention'
ERROR_ALREADY_SERVED = 'already_served'
ERROR_NONEXISTENT_FILE = 'nonexistent_file'
ERROR_BUSY_FILE = 'busy_file'
