CHUNK_SIZE = 8192
BUFFER_SIZE = 8192

TIMEOUT_DOWNLOAD = 15
TIMEOUT_UPLOAD = 4
TIMEOUT_TIMER = 2
WINDOW_SIZE = 5

ENCODING = "utf-8"
PADDING = "0"
SEQ_LEN = 8

MSG_INTENTION_UPLOAD = "upload"
MSG_INTENTION_DOWNLOAD = "download"
MSG_CONNECTION_ACK = "connection_ack"

ERROR_INVALID_PARAMETERS = "invalid_parameters"
ERROR_INVALID_INTENTION = "invalid_intention"
ERROR_ALREADY_SERVED = "already_served"
ERROR_NONEXISTENT_FILE = "nonexistent_file"
ERROR_BUSY_FILE = "busy_file"
